# Generated by Django 4.1.7 on 2023-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.IntegerField()),
                ('day', models.IntegerField()),
                ('ice', models.IntegerField()),
            ],
        ),
    ]
